# EDGE
windowrule = tile, class:^(microsoft-edge)$


# ZED основное окно
windowrule = opacity 0.95 0.95, class:^(zeditor)$

# ZED popup окна
windowrule = float, opacity 0.9 0.9, class:^(zeditor)

# NEMO основное окно - floating mode for file manager
windowrule = float, class:^(nemo)$
windowrule = center, class:^(nemo)$
windowrule = size 1200 700, class:^(nemo)$

# NEMO popup (Properties, Open With)
windowrule = float, pin, class:^(nemo)$, type:dialog

# Заглушка для пустых XWayland окон
windowrule = float, fullscreen 0, pinned 0, focus 0, class:^$, xwayland 1
